name: test-assignment-ticketing-system

services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=pass"
    ports:
      - "5432:5432"
  redis:
    image: "redis:7.2-alpine"
    ports:
      - "6379:6379"
